apiVersion: apps/v1
kind: Deployment
metadata:
  name: wms-ui-deployment  # название объекта Deployment
  labels:
    app: wms-ui      # (опционально) тэг, используется как селектор
spec:
  selector:
    matchLabels:
      app: wms-ui
      tier: frontend    # (опционально) тэг, используется как селектор
  replicas: 1          # количество одновременно работающих копий
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: wms-ui   # тэг, используется как селектор
        tier: frontend        # (опционально) тэг, используется как селектор
    spec:
      containers:
      - name: wms-ui             # имя контейнера
        image: harbor.technodom.kz/wms/wms-ui:stage # приватный докер реестр
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"             # запрашиваемый объем для деплоя - следует понимать, как планируемый необходимый объем ресурса для нормальной работы
            memory: "100Mi"          # запрашиваемый объем для деплоя - следует понимать, как планируемый необходимый объем ресурса для нормальной работы
          limits:
            cpu: "50m"             # максимально допустимый объем ресурса для работы сверх расчетной нагрузки - контейнер не сможет превысить данный лимит, работа продолжится не выходя за рамки данного лимита
            memory: "100Mi"          # максимально допустимый объем ресурса для работы сверх расчетной нагрузки - при превышении данного лимита контейнер будет принудительно перезапущен (сброшен/рестартован)
      imagePullSecrets:
      - name: harbor-pull-secret  # объект секрет для авторизации в приватном докер реестре
---
apiVersion: v1
kind: Service
metadata:
  name: wms-ui            # название объекта Service
  labels:
    app: wms-ui       # тэг для объекта Service
    tier: frontend          # (опционально) дополнительный тэг для объекта Service
spec:
  type: NodePort            # тип доступа к объекту Service извне кластера
  ports:
  - port: 80                # на какой порт мапится объект Service внутри кластера
    nodePort: 32697
  selector:
    app: wms-ui     # селектор - для каких объектов этот Service
    tier: frontend
